In [146]:
import numpy as np
import pandas as pd
from joblib import load
import os

In [147]:
os.chdir(os.getcwd())

# Defining grt end-members

In [148]:
# chemical format SiO2, TiO2, Al2O3, FeO, MnO, MgO, CaO, Na2O, K2O, P2O5, CO2
alm =     np.array([3,   0,    1,     3,   0,   0,   0,    0,   0,   0,   0])
py =      np.array([3,   0,    1,     0,   0,   3,   0,    0,   0,   0,   0])
sps =      np.array([3,   0,   1,     0,   3,  0,    0,    0,   0,   0,   0])

alm = 100 * alm / sum(alm)
py = 100 * py / sum(py)
sps = 100 * sps / sum(sps)

In [149]:
def make_almpy(interval = 0.1):
    alm =     np.array([3,   0,    1,     3,   0,   0,   0,    0,   0,   0,   0])
    py =      np.array([3,   0,    1,     0,   0,   3,   0,    0,   0,   0,   0])
    alm = 100 * alm / sum(alm)
    py = 100 * py / sum(py)
    femg = np.array([])
    for i in np.arange(0,1 + interval,interval):
        s = round(i,2)
        comp = (alm * s) + (py * (1 - s))
        # print(comp)
        if (i == 0):
            femg = comp
        else:
            femg = np.vstack((femg,comp))
    femg = np.round(femg,4)
    return(femg)

def make_grt(interval = 0.1):
    femg = make_almpy(interval)
    sps =      np.array([3,   0,   1,     0,   3,  0,    0,    0,   0,   0,   0])
    sps = 100 * sps / sum(sps)
    c = 0
    grt = np.array([])
    for i in np.arange(0,np.shape(femg)[0]):
        for j in np.arange(0,1 + interval, interval):
            comp = sps * j + (femg[i] * (1 - j))
            c = c + 1
            if (c == 1):
                grt = comp
            else:
                grt = np.vstack((grt,comp))
    grt = np.round(grt,4)
    return(grt)

In [150]:
make_grt(0.1)

array([[42.8571,  0.    , 14.2857, ...,  0.    ,  0.    ,  0.    ],
       [42.8571,  0.    , 14.2857, ...,  0.    ,  0.    ,  0.    ],
       [42.8571,  0.    , 14.2857, ...,  0.    ,  0.    ,  0.    ],
       ...,
       [42.8571,  0.    , 14.2857, ...,  0.    ,  0.    ,  0.    ],
       [42.8571,  0.    , 14.2857, ...,  0.    ,  0.    ,  0.    ],
       [42.8571,  0.    , 14.2857, ...,  0.    ,  0.    ,  0.    ]])

In [151]:
make_almpy(0.1)

array([[42.8571,  0.    , 14.2857,  0.    ,  0.    , 42.8571,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ],
       [42.8571,  0.    , 14.2857,  4.2857,  0.    , 38.5714,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ],
       [42.8571,  0.    , 14.2857,  8.5714,  0.    , 34.2857,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ],
       [42.8571,  0.    , 14.2857, 12.8571,  0.    , 30.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ],
       [42.8571,  0.    , 14.2857, 17.1429,  0.    , 25.7143,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ],
       [42.8571,  0.    , 14.2857, 21.4286,  0.    , 21.4286,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ],
       [42.8571,  0.    , 14.2857, 25.7143,  0.    , 17.1429,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ],
       [42.8571,  0.    , 14.2857, 30.    ,  0.    , 12.8571,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ],
       [42.8571,  0.    , 14.2857, 34.2857,  0.    ,  8.5714,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ],
       [42.8571,  0.    , 14.2857, 38.5714,  0.    ,  4.2857,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ],
       [42.8571,  0.    , 14.2857, 42.8571,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ]])

In [152]:
grt = make_grt(0.01)
grt = pd.DataFrame(grt, columns = ["SiO2", "TiO2", "Al2O3", "FeO", "MnO", "MgO", "CaO", "Na2O", "K2O", "P2O5", "CO2"])
grt

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5,CO2
0,42.8571,0.0,14.2857,0.0000,0.0000,42.8571,0.0,0.0,0.0,0.0,0.0
1,42.8571,0.0,14.2857,0.0000,0.4286,42.4285,0.0,0.0,0.0,0.0,0.0
2,42.8571,0.0,14.2857,0.0000,0.8571,42.0000,0.0,0.0,0.0,0.0,0.0
3,42.8571,0.0,14.2857,0.0000,1.2857,41.5714,0.0,0.0,0.0,0.0,0.0
4,42.8571,0.0,14.2857,0.0000,1.7143,41.1428,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
10196,42.8571,0.0,14.2857,1.7143,41.1429,0.0000,0.0,0.0,0.0,0.0,0.0
10197,42.8571,0.0,14.2857,1.2857,41.5714,0.0000,0.0,0.0,0.0,0.0,0.0
10198,42.8571,0.0,14.2857,0.8571,42.0000,0.0000,0.0,0.0,0.0,0.0,0.0
10199,42.8571,0.0,14.2857,0.4286,42.4286,0.0000,0.0,0.0,0.0,0.0,0.0
10200,42.8571,0.0,14.2857,0.0000,42.8571,0.0000,0.0,0.0,0.0,0.0,0.0

# Load model (and other files) and make predictions

In [153]:
mdl = "KNN"
combination = "C1"

In [154]:
if (mdl == "KNN"):
    path = r"C:\Users\naik3\Documents\Research\Mineral identifier ann IISER Mohali\Additional machine learning algos\KNN\\"
if (mdl == "SVM"):
    path = r"C:\Users\naik3\Documents\Research\Mineral identifier ann IISER Mohali\Additional machine learning algos\SVM\\"
if (mdl == "RF"):
    path = r"C:\Users\naik3\Documents\Research\Mineral identifier ann IISER Mohali\Additional machine learning algos\RF\\"

if (combination != "C4"):
    model = mdl + "_" + combination + ".mdl"
    labeler = "Labeler"+ "_" + mdl + "_" + combination + ".lbl"
    if (mdl != "RF"):
        scaler = "Scaler" + "_" + mdl + "_" + combination + ".scl"
    print(model, scaler, labeler)
else:
    model = mdl + "_" + combination + "_6_components" + ".mdl"
    labeler = "Labeler"+ "_" + mdl + "_" + combination + "_6_components" + ".lbl"
    pc = "PCA_" + mdl + "_" + combination + "_6_components" + ".pc"
    if (mdl != "RF"):
        scaler = "Scaler" + "_" + mdl + "_" + combination + "_6_components" + ".scl"
    print(model, scaler, labeler, pc)

KNN_C1.mdl Scaler_KNN_C1.scl Labeler_KNN_C1.lbl

In [155]:
model = load(path + model)
if (mdl != "RF"):
    scaler = load(path + scaler)
labeler = load(path + labeler)

if (combination == "C4"):
    pc_model = load(path + pc)
    
c = grt.columns

if ("PredMin" in c):
    grt.pop("PredMin")
if ("Total" in c):
    grt.pop("Total")

In [156]:
grt1 = grt.copy()

if (combination == "C2"):
    grt1["M"] = grt1["FeO"] + grt1["MnO"] + grt1["MgO"]
    grt1.drop(columns=["FeO","MnO","MgO"])
    grt1 = grt1[["SiO2", "TiO2", "Al2O3", "M", "CaO", "Na2O", "K2O", "P2O5", "CO2"]]
    
if (combination == "C3"):
    grt1["M"] = grt1["FeO"] + grt1["MnO"] + grt1["MgO"]
    grt1["A"] = grt1["Na2O"] + grt1["K2O"]
    grt1.drop(columns=["FeO","MnO","MgO","Na2O","K2O"])
    grt1 = grt1[["SiO2", "TiO2", "Al2O3", "M", "CaO", "A", "P2O5", "CO2"]]

if (combination == "C4"):
    grt1 = grt1[["SiO2", "TiO2", "Al2O3", "FeO", "MnO", "MgO", "CaO", "Na2O", "K2O", "P2O5", "CO2"]]
    if (mdl != "RF"):
        grt1 = scaler.transform(grt1)
    data_scaled = pc_model.transform(grt1)

grt1

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5,CO2
0,42.8571,0.0,14.2857,0.0000,0.0000,42.8571,0.0,0.0,0.0,0.0,0.0
1,42.8571,0.0,14.2857,0.0000,0.4286,42.4285,0.0,0.0,0.0,0.0,0.0
2,42.8571,0.0,14.2857,0.0000,0.8571,42.0000,0.0,0.0,0.0,0.0,0.0
3,42.8571,0.0,14.2857,0.0000,1.2857,41.5714,0.0,0.0,0.0,0.0,0.0
4,42.8571,0.0,14.2857,0.0000,1.7143,41.1428,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
10196,42.8571,0.0,14.2857,1.7143,41.1429,0.0000,0.0,0.0,0.0,0.0,0.0
10197,42.8571,0.0,14.2857,1.2857,41.5714,0.0000,0.0,0.0,0.0,0.0,0.0
10198,42.8571,0.0,14.2857,0.8571,42.0000,0.0000,0.0,0.0,0.0,0.0,0.0
10199,42.8571,0.0,14.2857,0.4286,42.4286,0.0000,0.0,0.0,0.0,0.0,0.0
10200,42.8571,0.0,14.2857,0.0000,42.8571,0.0000,0.0,0.0,0.0,0.0,0.0

In [157]:
if (combination != "C4"):
    if (mdl != "RF"):
        data_scaled = scaler.transform(grt1)
    elif (mdl == "RF"):
        data_scaled = grt1.copy()

In [158]:
data_scaled

array([[ 0.27085444, -0.33264039,  0.14142998, ..., -0.38481125,
        -0.1751544 , -0.16863647],
       [ 0.27085444, -0.33264039,  0.14142998, ..., -0.38481125,
        -0.1751544 , -0.16863647],
       [ 0.27085444, -0.33264039,  0.14142998, ..., -0.38481125,
        -0.1751544 , -0.16863647],
       ...,
       [ 0.27085444, -0.33264039,  0.14142998, ..., -0.38481125,
        -0.1751544 , -0.16863647],
       [ 0.27085444, -0.33264039,  0.14142998, ..., -0.38481125,
        -0.1751544 , -0.16863647],
       [ 0.27085444, -0.33264039,  0.14142998, ..., -0.38481125,
        -0.1751544 , -0.16863647]])

In [159]:
pred = model.predict(data_scaled)
predictions = labeler.inverse_transform(pred)

In [160]:
predictions[predictions != "Grt"]

array(['Crd', 'Crd', 'Crd', ..., 'Px', 'Px', 'Px'], dtype=object)

In [161]:
x = model.predict_proba(data_scaled)
grt["Total"] = grt.sum(axis = 1)
grt["PredMin"] = predictions
grt_prob = pd.DataFrame(x, columns = labeler.classes_, index = grt.index)

In [162]:
grt_final = pd.concat([grt,grt_prob], axis = 1)

In [163]:
grt_final

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5,...,Ilm,Mag/Hem,Ms,Ol,Px,Qz,Rt,Spl,St,Ttn
0,42.8571,0.0,14.2857,0.0000,0.0000,42.8571,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,42.8571,0.0,14.2857,0.0000,0.4286,42.4285,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,42.8571,0.0,14.2857,0.0000,0.8571,42.0000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,42.8571,0.0,14.2857,0.0000,1.2857,41.5714,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,42.8571,0.0,14.2857,0.0000,1.7143,41.1428,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10196,42.8571,0.0,14.2857,1.7143,41.1429,0.0000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10197,42.8571,0.0,14.2857,1.2857,41.5714,0.0000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10198,42.8571,0.0,14.2857,0.8571,42.0000,0.0000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10199,42.8571,0.0,14.2857,0.4286,42.4286,0.0000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10200,42.8571,0.0,14.2857,0.0000,42.8571,0.0000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [164]:
grt_final.Total

0         99.9999
1         99.9999
2         99.9999
3         99.9999
4         99.9999
           ...
10196    100.0000
10197     99.9999
10198     99.9999
10199    100.0000
10200     99.9999
Name: Total, Length: 10201, dtype: float64

In [165]:
output_file = "Grt_prediction_for_" + mdl + "_" + combination + ".csv"
output_file

'Grt_prediction_for_KNN_C1.csv'

In [166]:
grt_final.to_csv(output_file)