In [32]:
import pandas as pd
from joblib import load
from sklearn.metrics import f1_score,confusion_matrix
import numpy as np

In [33]:
oxide = pd.read_excel(r"D:/Research/Mineral identifier ann IISER Mohali/new random comp generator/GEOROC data/processed minerals/oxide_data.xlsx", sheet_name="Sheet1",index_col=0,header=0)

def normalize(data,n=100):
    s = n/data.sum(axis=1)
    data_formatted = data.mul(s,axis=0)
    return(data_formatted)
    
def wt_to_mol(data, oxide = oxide):
    data[data<=2] = 0
    if 'Total' in data.columns:
        data.pop('Total')
    oxlist1 = data.columns
    oxide = oxide.T[oxlist1].iloc[0, :]
    data = normalize(data,100)
    data_f = data.div(oxide,axis=1)
    data_f = normalize(data_f)
    return(data_f.round(2))

# file = r"D:/Research/Mineral identifier ann IISER Mohali/new random comp generator/GEOROC data/processed minerals/molar tables/new data/compiled9_2.xlsx"
# file_test = r"D:/Research/Mineral identifier ann IISER Mohali/new random comp generator/External test data/Mineral data combined_RSandSS_mol1.xlsx"
# file_test = r"D:\Research\Mineral identifier ann IISER Mohali\new random comp generator\External test data\Mineral data combined_DHZ,PSandSS.xlsx"
# file_test = r"D:\Research\Mineral identifier ann IISER Mohali\new random comp generator\External test data\test_data_deerhowiezussmann.xlsx"
file_test = r"D:\Research\Mineral identifier ann IISER Mohali\ms and reference papers\MinNet ver 4 for submitted to AmMin\Revision 1\AmMin revision 1\Sir modified files\External dataset 2\Processed\name shortened\Combined_PantSir.xlsx"

# data = pd.read_excel(file,header=0,index_col=0)
data_test = pd.read_excel(file_test,header=0,index_col=0)
m = len(data_test['Mineral'].unique())
acc_table = np.zeros((m+1,5))

data_test

,SiO2,MgO,FeO,TiO2,Al2O3,MnO,CaO,Na2O,K2O,Cr2O3,...,Er2O3,Yb2O3,V2O3,CoO,ZnO,ZrO2,CuO,Total,Mineral,Source
1,40.79,48.85,10.16,0.000,0.00,0.000,0.000,0.000,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,99.800,Ol,Batanova et al 2019
2,40.47,48.68,10.20,0.000,0.00,0.000,0.000,0.000,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,99.350,Ol,Batanova et al 2019
3,40.96,48.83,10.16,0.000,0.00,0.000,0.000,0.000,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,99.950,Ol,Batanova et al 2019
4,55.77,6.37,0.02,0.010,23.62,0.000,0.000,0.100,11.23,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,97.120,Ms,Biino and Gröning - 1998
5,55.65,6.29,0.01,0.000,23.67,0.000,0.000,0.080,11.17,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96.870,Ms,Biino and Gröning - 1998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1422,48.50,0.00,4.40,0.027,26.50,1.327,0.008,0.324,10.20,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,91.286,Ms,Xu et al 2023
1423,47.40,1.26,4.07,0.363,32.50,0.221,0.017,0.617,9.57,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96.018,Ms,Xu et al 2023
1424,45.60,0.52,4.76,0.357,32.00,0.694,0.011,0.699,9.90,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,94.541,Ms,Xu et al 2023
1425,47.80,0.00,0.93,0.067,36.60,0.349,0.002,0.327,10.31,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96.385,Ms,Xu et al 2023
1426,46.10,1.15,8.10,0.532,27.60,1.120,0.013,0.248,9.50,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,94.363,Ms,Xu et al 2023

In [34]:
if 'Mineral' in data_test.columns:
    minerals = data_test.pop("Mineral")
if 'Source' in data_test.columns:
    data_test.pop("Source")

# if 'Fe2O3' in data_test.columns:
#     data_test['FeO'] = data_test['FeO'] + (0.8998 * data_test['Fe2O3'])
#     data_test.pop('Fe2O3')

metrics = 'weighted'
if 'F' in data_test.columns:
    data_test.pop('F')
if 'Cl' in data_test.columns:
    data_test.pop('Cl')

data_test = normalize(data_test)

if 'Total' not in data_test.columns:
    data_test['Total'] = data_test.iloc[:,:-2].sum(axis=1)
if 'P2O5' not in data_test.columns:
    data_test['P2O5']=0
if 'CO2' not in data_test.columns:
    data_test['CO2']=0
    data_test.loc[minerals=='Cb','CO2'] = data_test['Total'] - data_test[['FeO','MnO','MgO','CaO']].sum(axis=1)

In [35]:
data_test.fillna(0,inplace=True)

In [36]:
data_test = wt_to_mol(data_test,oxide)
if 'SrO' in data_test.columns:
    data_test['CaO'] = data_test['CaO'] + data_test['SrO']
    data_test.pop('SrO')
if 'BaO' in data_test.columns:
    data_test['CaO'] = data_test['CaO'] + data_test['BaO']
    data_test.pop('BaO')
if 'Cr2O3' in data_test.columns:
    data_test['Al2O3'] = data_test['Al2O3'] + data_test['Cr2O3']
    data_test.pop('Cr2O3')
if 'ZnO' in data_test.columns:
    data_test['FeO'] = data_test['FeO'] + data_test['ZnO']
    data_test.pop('ZnO')
if 'CoO' in data_test.columns:
    data_test['FeO'] = data_test['FeO'] + data_test['CoO']
    data_test.pop('CoO')

In [37]:
data_test_original = data_test.copy()

# Raw Input (C1)

In [38]:
model = load("RF_C1.mdl")
# scaler = load("Scaler_C1.scl")
labeler = load("Labeler_C1.lbl")

data_test = data_test_original.copy()
data_test1 = data_test.copy()
# data_test1['M'] = data_test1[["FeO","MnO","MgO"]].sum(axis=1)
data_test1 = data_test1[['SiO2','TiO2','Al2O3','FeO','MnO','MgO','CaO','Na2O','K2O','P2O5','CO2']]

# m = data_test1[["FeO","MnO","MgO"]]sum(axis=1)

# data_test_scaled = scaler.transform(data_test1)

data_test_scaled =data_test1.copy()
test_target = labeler.transform(minerals)
pred_label = model.predict(data_test_scaled)
a = round(f1_score(test_target, pred_label, average=metrics,zero_division=0),4)*100
acc_table[0,0] = a
print("Overall: "+str(a))

labels = labeler.transform(minerals.unique())
labels1 = labeler.inverse_transform(labels)

for n,i in enumerate(labels1):
    # data_test2 = scaler.transform(data_test1.loc[minerals==i,:])
    data_test2 = data_test1.loc[minerals==i,:].copy()

    minerals2 = labeler.transform(minerals.loc[minerals == i])
    pred_label2 = model.predict(data_test2)
    a = round(f1_score(minerals2, pred_label2, average=metrics,zero_division=0),4)*100
    acc_table[n+1,0] = a
    print(labels1[n]+": "+str(round(a,2)))

data_mismatch = data_test.loc[test_target != pred_label,:]
minerals_mismatch = minerals.loc[test_target != pred_label]
data_mismatch = pd.concat([data_mismatch,minerals_mismatch],axis=1)
data_mismatch

C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

Overall: 97.18
Ol: 100.0
Ms: 98.7
Grt: 83.44
Amp: 98.23
Px: 95.71
Spl: 100.0
Fsp: 99.56
Bt: 100.0
Ttn: 100.0
Ap: 100.0

C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

,SiO2,MgO,FeO,TiO2,Al2O3,MnO,CaO,Na2O,K2O,P2O5,...,Sm2O3,Gd2O3,Dy2O3,Er2O3,Yb2O3,V2O3,ZrO2,CuO,CO2,Mineral
18,45.840504,0.0,28.607461,0.0,13.61215,0.0,11.939885,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
66,51.715743,14.21163,14.840854,0.0,9.981523,0.0,9.25025,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
68,50.033745,22.631168,7.420503,0.0,7.967547,0.0,11.947036,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
834,51.060666,6.660744,0.0,0.0,19.671164,0.0,22.607426,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fsp
867,42.048091,20.171241,10.876221,3.581093,9.354042,0.0,13.969312,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
869,59.307416,0.0,27.103482,0.0,0.0,0.0,0.0,13.589102,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
871,44.359125,21.170889,12.046923,0.0,9.609952,0.0,12.813111,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
872,42.645517,27.608024,3.742378,0.0,11.013908,0.0,14.990172,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
922,53.51399,26.335675,5.756234,0.0,0.0,0.0,14.394102,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
923,57.865942,13.418328,0.0,0.0,7.848912,0.0,14.68308,6.183738,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
924,52.486774,28.751507,4.341819,0.0,0.0,0.0,14.4199,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
925,52.599729,26.577983,4.916265,0.0,0.0,0.0,15.906024,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
982,33.998826,0.0,21.241782,0.0,0.0,0.0,34.182773,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
983,34.940324,0.0,20.480125,0.0,0.0,0.0,34.552175,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
984,34.91768,0.0,19.257673,0.0,0.0,0.0,36.319321,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
985,33.524211,0.0,17.164556,5.675527,0.0,0.0,35.6129,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
986,33.374935,0.0,15.120956,8.587678,0.0,0.0,36.226772,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1381,38.766588,0.0,15.322941,0.0,5.926097,0.0,39.984375,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1384,38.780308,0.0,18.007604,0.0,4.444321,0.0,38.767767,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1386,39.176186,0.0,15.753822,0.0,5.146634,0.0,39.923358,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1387,39.018624,0.0,15.206363,0.0,6.045065,0.0,39.729947,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1388,39.377829,0.0,14.861485,0.0,5.917564,0.0,39.843123,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1389,38.775031,0.0,16.42095,0.0,4.985521,0.0,39.818497,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1392,38.811316,0.0,15.338785,0.0,5.920888,0.0,39.929011,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1393,39.866515,0.0,13.399923,0.0,6.614022,0.0,40.119541,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1394,39.061842,0.0,15.409243,0.0,6.244009,0.0,39.284906,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1395,38.506524,0.0,17.235952,0.0,5.314728,0.0,38.942795,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1396,39.059923,0.0,14.874445,0.0,6.613969,0.0,39.451663,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1397,37.604513,0.0,19.300011,0.0,4.367389,0.0,38.728088,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1398,39.750827,0.0,14.333249,0.0,6.424865,0.0,39.49106,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1399,38.848407,0.0,17.563182,0.0,4.744793,0.0,38.843618,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1400,39.743646,0.0,14.443252,0.0,6.460405,0.0,39.352698,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1401,37.490941,0.0,24.718633,0.0,0.0,0.0,37.790425,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1402,39.310877,0.0,16.55845,0.0,5.184994,0.0,38.945679,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1403,37.102744,0.0,24.583979,0.0,0.0,0.0,38.313277,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1404,36.890089,0.0,24.924823,0.0,0.0,0.0,38.185089,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1405,38.876185,0.0,17.254553,0.0,4.602157,0.0,39.267105,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1406,37.492165,0.0,24.863396,0.0,0.0,0.0,37.644439,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1419,65.163999,0.0,6.693326,0.0,19.518935,0.0,0.0,0.0,8.623739,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms

# C2

In [39]:
model = load("RF_C2.mdl")
# scaler = load("Scaler_C2.scl")
labeler = load("Labeler_C2.lbl")

data_test = data_test_original.copy()

data_test1 = data_test.copy()
data_test1['M'] = data_test1[["FeO","MnO","MgO"]].sum(axis=1)
data_test1 = data_test1[['SiO2','TiO2','Al2O3','M','CaO','Na2O','K2O','P2O5','CO2']]

# m = data_test1[["FeO","MnO","MgO"]]sum(axis=1)

# data_test_scaled = scaler.transform(data_test1)
data_test_scaled =data_test1.copy()
test_target = labeler.transform(minerals)
pred_label = model.predict(data_test_scaled)
a = round(f1_score(test_target, pred_label, average=metrics,zero_division=0),4)*100
acc_table[0,1] = a
print("Overall: "+str(a))

labels = labeler.transform(minerals.unique())
labels1 = labeler.inverse_transform(labels)

for n,i in enumerate(labels1):
    # data_test2 = scaler.transform(data_test1.loc[minerals==i,:])
    data_test2 = data_test1.loc[minerals==i,:].copy()

    minerals2 = labeler.transform(minerals.loc[minerals == i])
    pred_label2 = model.predict(data_test2)
    a = round(f1_score(minerals2, pred_label2, average=metrics,zero_division=0),4)*100
    acc_table[n+1,1] = a
    print(labels1[n]+": "+str(round(a,2)))

data_mismatch = data_test.loc[test_target != pred_label,:]
minerals_mismatch = minerals.loc[test_target != pred_label]
data_mismatch = pd.concat([data_mismatch,minerals_mismatch],axis=1)
# data_mismatch['Pred'] = labeler.inverse_transform(pred_label)
data_mismatch

C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

Overall: 97.04
Ol: 100.0
Ms: 94.59
Grt: 84.85
Amp: 97.32
Px: 96.45
Spl: 100.0
Fsp: 100.0
Bt: 99.82
Ttn: 100.0
Ap: 100.0

C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

,SiO2,MgO,FeO,TiO2,Al2O3,MnO,CaO,Na2O,K2O,P2O5,...,Sm2O3,Gd2O3,Dy2O3,Er2O3,Yb2O3,V2O3,ZrO2,CuO,CO2,Mineral
4,64.587033,10.997559,0.0,0.0,16.119588,0.0,0.0,0.0,8.295821,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms
5,64.633747,10.890729,0.0,0.0,16.200252,0.0,0.0,0.0,8.275272,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms
17,45.482901,0.0,29.810474,0.0,13.607599,0.0,11.099025,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
18,45.840504,0.0,28.607461,0.0,13.61215,0.0,11.939885,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
66,51.715743,14.21163,14.840854,0.0,9.981523,0.0,9.25025,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
68,50.033745,22.631168,7.420503,0.0,7.967547,0.0,11.947036,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
75,48.231447,25.375501,10.503592,0.0,5.554196,0.0,10.335263,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
717,45.416186,35.67116,6.281221,0.0,12.631434,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
867,42.048091,20.171241,10.876221,3.581093,9.354042,0.0,13.969312,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
871,44.359125,21.170889,12.046923,0.0,9.609952,0.0,12.813111,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
872,42.645517,27.608024,3.742378,0.0,11.013908,0.0,14.990172,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
876,56.035399,31.735211,4.55848,0.0,0.0,0.0,7.67091,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
889,55.617532,31.635973,4.718555,0.0,0.0,0.0,8.02794,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
922,53.51399,26.335675,5.756234,0.0,0.0,0.0,14.394102,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
923,57.865942,13.418328,0.0,0.0,7.848912,0.0,14.68308,6.183738,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
924,52.486774,28.751507,4.341819,0.0,0.0,0.0,14.4199,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
982,33.998826,0.0,21.241782,0.0,0.0,0.0,34.182773,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
983,34.940324,0.0,20.480125,0.0,0.0,0.0,34.552175,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
984,34.91768,0.0,19.257673,0.0,0.0,0.0,36.319321,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
985,33.524211,0.0,17.164556,5.675527,0.0,0.0,35.6129,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
986,33.374935,0.0,15.120956,8.587678,0.0,0.0,36.226772,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1022,47.694747,12.813526,19.606824,0.0,13.793935,0.0,0.0,0.0,6.090968,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bt
1384,38.780308,0.0,18.007604,0.0,4.444321,0.0,38.767767,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1395,38.506524,0.0,17.235952,0.0,5.314728,0.0,38.942795,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1397,37.604513,0.0,19.300011,0.0,4.367389,0.0,38.728088,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1399,38.848407,0.0,17.563182,0.0,4.744793,0.0,38.843618,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1401,37.490941,0.0,24.718633,0.0,0.0,0.0,37.790425,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1403,37.102744,0.0,24.583979,0.0,0.0,0.0,38.313277,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1404,36.890089,0.0,24.924823,0.0,0.0,0.0,38.185089,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1405,38.876185,0.0,17.254553,0.0,4.602157,0.0,39.267105,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1406,37.492165,0.0,24.863396,0.0,0.0,0.0,37.644439,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1408,46.037894,0.0,34.148953,0.0,14.562101,0.0,5.251052,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1409,48.223844,0.0,36.629626,0.0,15.146529,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1410,48.317889,0.0,36.4913,0.0,15.190811,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1411,48.409745,0.0,36.098709,0.0,15.491547,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1412,48.543643,0.0,36.35922,0.0,15.097137,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1413,48.158626,0.0,36.571271,0.0,15.270103,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1414,48.057343,0.0,36.728215,0.0,15.214442,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1415,45.726386,0.0,34.262828,0.0,14.421665,0.0,5.58912,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1419,65.163999,0.0,6.693326,0.0,19.518935,0.0,0.0,0.0,8.623739,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms
1422,65.273968,0.0,4.952341,0.0,21.017134,0.0,0.0,0.0,8.756557,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms

# C3

In [40]:
model = load("RF_C3.mdl")
# scaler = load("Scaler_C3.scl")
labeler = load("Labeler_C3.lbl")

data_test = data_test_original.copy()

data_test1 = data_test.copy()
data_test1['M'] = data_test1[["FeO","MnO","MgO"]].sum(axis=1)
data_test1['A'] = data_test1[["Na2O","K2O"]].sum(axis=1)
data_test1 = data_test1[['SiO2','TiO2','Al2O3','M','CaO','A','P2O5','CO2']]

# m = data_test1[["FeO","MnO","MgO"]]sum(axis=1)

# data_test_scaled = scaler.transform(data_test1)
data_test_scaled =data_test1.copy()
test_target = labeler.transform(minerals)
pred_label = model.predict(data_test_scaled)
a = round(f1_score(test_target, pred_label, average=metrics,zero_division=0),4)*100
acc_table[0,2] = a
print("Overall: "+str(a))

labels = labeler.transform(minerals.unique())
labels1 = labeler.inverse_transform(labels)

for n,i in enumerate(labels1):
    # data_test2 = scaler.transform(data_test1.loc[minerals==i,:])
    data_test2 = data_test1.loc[minerals==i,:].copy()

    minerals2 = labeler.transform(minerals.loc[minerals == i])
    pred_label2 = model.predict(data_test2)
    a = round(f1_score(minerals2, pred_label2, average=metrics,zero_division=0),4)*100
    acc_table[n+1,2] = a
    print(labels1[n]+": "+str(round(a,2)))

data_mismatch = data_test.loc[test_target != pred_label,:]
minerals_mismatch = minerals.loc[test_target != pred_label]
data_mismatch = pd.concat([data_mismatch,minerals_mismatch],axis=1)
data_mismatch

C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

Overall: 98.09
Ol: 100.0
Ms: 93.15
Grt: 93.85
Amp: 97.78
Px: 97.18
Spl: 100.0
Fsp: 100.0
Bt: 99.65
Ttn: 100.0
Ap: 100.0

C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

,SiO2,MgO,FeO,TiO2,Al2O3,MnO,CaO,Na2O,K2O,P2O5,...,Sm2O3,Gd2O3,Dy2O3,Er2O3,Yb2O3,V2O3,ZrO2,CuO,CO2,Mineral
4,64.587033,10.997559,0.0,0.0,16.119588,0.0,0.0,0.0,8.295821,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms
5,64.633747,10.890729,0.0,0.0,16.200252,0.0,0.0,0.0,8.275272,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms
66,51.715743,14.21163,14.840854,0.0,9.981523,0.0,9.25025,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
68,50.033745,22.631168,7.420503,0.0,7.967547,0.0,11.947036,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
75,48.231447,25.375501,10.503592,0.0,5.554196,0.0,10.335263,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
860,49.687519,0.0,24.52711,0.0,17.817903,0.0,0.0,0.0,7.967468,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bt
867,42.048091,20.171241,10.876221,3.581093,9.354042,0.0,13.969312,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
872,42.645517,27.608024,3.742378,0.0,11.013908,0.0,14.990172,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
876,56.035399,31.735211,4.55848,0.0,0.0,0.0,7.67091,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
889,55.617532,31.635973,4.718555,0.0,0.0,0.0,8.02794,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Amp
923,57.865942,13.418328,0.0,0.0,7.848912,0.0,14.68308,6.183738,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
924,52.486774,28.751507,4.341819,0.0,0.0,0.0,14.4199,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
982,33.998826,0.0,21.241782,0.0,0.0,0.0,34.182773,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
983,34.940324,0.0,20.480125,0.0,0.0,0.0,34.552175,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
984,34.91768,0.0,19.257673,0.0,0.0,0.0,36.319321,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
985,33.524211,0.0,17.164556,5.675527,0.0,0.0,35.6129,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
986,33.374935,0.0,15.120956,8.587678,0.0,0.0,36.226772,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1022,47.694747,12.813526,19.606824,0.0,13.793935,0.0,0.0,0.0,6.090968,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bt
1384,38.780308,0.0,18.007604,0.0,4.444321,0.0,38.767767,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1397,37.604513,0.0,19.300011,0.0,4.367389,0.0,38.728088,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1401,37.490941,0.0,24.718633,0.0,0.0,0.0,37.790425,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1403,37.102744,0.0,24.583979,0.0,0.0,0.0,38.313277,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1404,36.890089,0.0,24.924823,0.0,0.0,0.0,38.185089,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1406,37.492165,0.0,24.863396,0.0,0.0,0.0,37.644439,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1419,65.163999,0.0,6.693326,0.0,19.518935,0.0,0.0,0.0,8.623739,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms
1422,65.273968,0.0,4.952341,0.0,21.017134,0.0,0.0,0.0,8.756557,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms
1426,61.304652,0.0,9.008182,0.0,21.628725,0.0,0.0,0.0,8.058441,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms

# C4

In [41]:
model = load("RF_C4.mdl")
# scaler = load("Scaler_C4.scl")
labeler = load("Labeler_C4.lbl")

data_test = data_test_original.copy()

data_test1 = data_test.copy()
data_test1['M'] = data_test1[["FeO","MnO","MgO","CaO"]].sum(axis=1)
data_test1['A'] = data_test1[["CaO","Na2O","K2O"]].sum(axis=1)
data_test1 = data_test1[['SiO2','TiO2','Al2O3','M','A','P2O5','CO2']]

# m = data_test1[["FeO","MnO","MgO"]]sum(axis=1)

# data_test_scaled = scaler.transform(data_test1)
data_test_scaled =data_test1.copy()
test_target = labeler.transform(minerals)
pred_label = model.predict(data_test_scaled)
a = round(f1_score(test_target, pred_label, average=metrics,zero_division=0),4)*100
acc_table[0,3] = a
print("Overall: "+str(a))

labels = labeler.transform(minerals.unique())
labels1 = labeler.inverse_transform(labels)

for n,i in enumerate(labels1):
    # data_test2 = scaler.transform(data_test1.loc[minerals==i,:])
    data_test2 = data_test1.loc[minerals==i,:].copy()
    minerals2 = labeler.transform(minerals.loc[minerals == i])
    pred_label2 = model.predict(data_test2)
    a = round(f1_score(minerals2, pred_label2, average=metrics,zero_division=0),4)*100
    acc_table[n+1,3] = a
    print(labels1[n]+": "+str(round(a,2)))

data_mismatch = data_test.loc[test_target != pred_label,:]
minerals_mismatch = minerals.loc[test_target != pred_label]
data_mismatch = pd.concat([data_mismatch,minerals_mismatch],axis=1)
data_mismatch

C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

Overall: 92.05
Ol: 100.0
Ms: 100.0
Grt: 62.32
Amp: 99.12
Px: 96.45
Spl: 100.0
Fsp: 71.51
Bt: 99.47
Ttn: 100.0
Ap: 100.0

C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

,SiO2,MgO,FeO,TiO2,Al2O3,MnO,CaO,Na2O,K2O,P2O5,...,Sm2O3,Gd2O3,Dy2O3,Er2O3,Yb2O3,V2O3,ZrO2,CuO,CO2,Mineral
17,45.482901,0.0,29.810474,0.0,13.607599,0.0,11.099025,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
18,45.840504,0.0,28.607461,0.0,13.61215,0.0,11.939885,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
66,51.715743,14.21163,14.840854,0.0,9.981523,0.0,9.25025,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
68,50.033745,22.631168,7.420503,0.0,7.967547,0.0,11.947036,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
719,42.957666,29.502187,9.853502,0.0,12.519364,0.0,5.167281,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1411,48.409745,0.0,36.098709,0.0,15.491547,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1412,48.543643,0.0,36.35922,0.0,15.097137,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1413,48.158626,0.0,36.571271,0.0,15.270103,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1414,48.057343,0.0,36.728215,0.0,15.214442,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1415,45.726386,0.0,34.262828,0.0,14.421665,0.0,5.58912,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt

In [42]:
data_mismatch[data_mismatch['Mineral']=="Cb"]

Empty DataFrame
Columns: [SiO2, MgO, FeO, TiO2, Al2O3, MnO, CaO, Na2O, K2O, P2O5, NiO, Fe2O3, As2O3, Y2O3, La2O3, Ce2O3, Nd2O3, Pr2O3, ThO2, UO2, Nb2O5, Sm2O3, Gd2O3, Dy2O3, Er2O3, Yb2O3, V2O3, ZrO2, CuO, CO2, Mineral]
Index: []

[0 rows x 31 columns]

# C5

In [43]:
model = load("RF_C5_5_components.mdl")
# scaler = load("Scaler_C5_5_components.scl")
labeler = load("Labeler_C5_5_components.lbl")
pc = load("PCA_C5_5_components.pc")

data_test = data_test_original.copy()

data_test1 = data_test.copy()
data_test1 = data_test1[['SiO2','TiO2','Al2O3','FeO','MnO','MgO','CaO','Na2O','K2O','P2O5','CO2']]
# m = data_test1[["FeO","MnO","MgO"]]sum(axis=1)

# data_test_scaled = scaler.transform(data_test1)
data_test_scaled =data_test1.copy()
data_test_scaled = pc.transform(data_test_scaled)
test_target = labeler.transform(minerals)
pred_label = model.predict(data_test_scaled)
a = round(f1_score(test_target, pred_label, average=metrics,zero_division=0),4)*100
acc_table[0,4] = a
print("Overall: "+str(a))

labels = labeler.transform(minerals.unique())
labels1 = labeler.inverse_transform(labels)

for n,i in enumerate(labels1):
    # data_test2 = scaler.transform(data_test1.loc[minerals==i,:])
    data_test2 = data_test1.loc[minerals==i,:].copy()
    data_test2 = pc.transform(data_test2)
    minerals2 = labeler.transform(minerals.loc[minerals == i])
    pred_label2 = model.predict(data_test2)
    a = round(f1_score(minerals2, pred_label2, average=metrics,zero_division=0),4)*100
    acc_table[n+1,4] = a
    print(labels1[n]+": "+str(round(a,2)))

data_mismatch = data_test.loc[test_target != pred_label,:]
minerals_mismatch = minerals.loc[test_target != pred_label]
data_mismatch = pd.concat([data_mismatch,minerals_mismatch],axis=1)
data_mismatch

C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(

Overall: 96.86
Ol: 100.0
Ms: 91.67
Grt: 80.5
Amp: 100.0
Px: 96.45
Spl: 100.0
Fsp: 100.0
Bt: 99.65
Ttn: 100.0
Ap: 100.0

C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\naik3\Documents\python_geology\granite_mineralization\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(

,SiO2,MgO,FeO,TiO2,Al2O3,MnO,CaO,Na2O,K2O,P2O5,...,Sm2O3,Gd2O3,Dy2O3,Er2O3,Yb2O3,V2O3,ZrO2,CuO,CO2,Mineral
4,64.587033,10.997559,0.0,0.0,16.119588,0.0,0.0,0.0,8.295821,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms
5,64.633747,10.890729,0.0,0.0,16.200252,0.0,0.0,0.0,8.275272,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms
66,51.715743,14.21163,14.840854,0.0,9.981523,0.0,9.25025,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
68,50.033745,22.631168,7.420503,0.0,7.967547,0.0,11.947036,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
702,42.575329,31.681606,7.248057,0.0,13.297111,0.0,5.197897,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
703,42.994219,30.6739,7.044727,0.0,13.331604,0.0,5.95555,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
704,42.647196,32.853384,6.079312,0.0,13.413531,0.0,5.006577,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
706,42.199877,32.05728,7.559745,0.0,13.445368,0.0,4.73773,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
707,44.317436,34.838357,6.451083,0.0,14.393125,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
709,42.726839,32.862711,5.700509,0.0,13.169931,0.0,5.54001,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
712,44.665932,33.372929,8.410872,0.0,13.550266,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
714,43.067097,33.535465,6.036667,0.0,12.70741,0.0,4.65336,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
715,42.674905,33.274448,6.278588,0.0,12.615749,0.0,5.156311,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
717,45.416186,35.67116,6.281221,0.0,12.631434,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
718,42.711791,32.908271,5.777689,0.0,13.15696,0.0,5.445289,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
719,42.957666,29.502187,9.853502,0.0,12.519364,0.0,5.167281,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
720,43.637658,31.536687,7.350072,0.0,12.767291,0.0,4.708291,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
721,43.051321,33.834763,5.442955,0.0,12.295022,0.0,5.375939,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
860,49.687519,0.0,24.52711,0.0,17.817903,0.0,0.0,0.0,7.967468,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bt
922,53.51399,26.335675,5.756234,0.0,0.0,0.0,14.394102,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
923,57.865942,13.418328,0.0,0.0,7.848912,0.0,14.68308,6.183738,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
924,52.486774,28.751507,4.341819,0.0,0.0,0.0,14.4199,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Px
982,33.998826,0.0,21.241782,0.0,0.0,0.0,34.182773,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
983,34.940324,0.0,20.480125,0.0,0.0,0.0,34.552175,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
984,34.91768,0.0,19.257673,0.0,0.0,0.0,36.319321,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
985,33.524211,0.0,17.164556,5.675527,0.0,0.0,35.6129,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
986,33.374935,0.0,15.120956,8.587678,0.0,0.0,36.226772,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1003,63.113874,7.659704,0.0,0.0,21.872565,0.0,0.0,0.0,7.353858,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms
1026,40.009523,19.400536,20.383994,0.0,14.307786,0.0,0.0,0.0,5.898162,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bt
1384,38.780308,0.0,18.007604,0.0,4.444321,0.0,38.767767,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1386,39.176186,0.0,15.753822,0.0,5.146634,0.0,39.923358,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1389,38.775031,0.0,16.42095,0.0,4.985521,0.0,39.818497,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1395,38.506524,0.0,17.235952,0.0,5.314728,0.0,38.942795,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1397,37.604513,0.0,19.300011,0.0,4.367389,0.0,38.728088,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1399,38.848407,0.0,17.563182,0.0,4.744793,0.0,38.843618,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1401,37.490941,0.0,24.718633,0.0,0.0,0.0,37.790425,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1402,39.310877,0.0,16.55845,0.0,5.184994,0.0,38.945679,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1403,37.102744,0.0,24.583979,0.0,0.0,0.0,38.313277,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1404,36.890089,0.0,24.924823,0.0,0.0,0.0,38.185089,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1405,38.876185,0.0,17.254553,0.0,4.602157,0.0,39.267105,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1406,37.492165,0.0,24.863396,0.0,0.0,0.0,37.644439,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Grt
1419,65.163999,0.0,6.693326,0.0,19.518935,0.0,0.0,0.0,8.623739,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms
1422,65.273968,0.0,4.952341,0.0,21.017134,0.0,0.0,0.0,8.756557,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms
1426,61.304652,0.0,9.008182,0.0,21.628725,0.0,0.0,0.0,8.058441,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ms

In [13]:
l=['Overall']
l.extend(list(minerals.unique()))
acc_table = pd.DataFrame(acc_table,
                          columns=["C1", "C2", "C3", "C4", "C5"],index=l)
acc_table.to_excel("F1-score Accuracy report for RF_test.xlsx")